# Finding other ways to get data

In [1]:
import pandas as pd

As it so happens..... pandas also has a function for importing Excel spreadsheets (i.e. we don't necessarily need the openpyxl if we aren't doing more sophisticated things with Excel)

In [2]:
pd.read_excel('data/iris-excel-starter.xlsx')

       species petalLength  petalWidth  sepalLength  sepalWidth
0       setosa         1.4         0.2          5.1         3.5
1       setosa         1.4         0.2          4.9        30.0
2       setosa         1.3         0.2          4.7         3.2
3       setosa         1.5         0.2          4.6         3.1
4       setosa         1.4         0.2          5.0         3.6
..         ...         ...         ...          ...         ...
145  virginica         5.2         2.3          NaN         3.0
146  virginica           5         1.9          NaN         2.5
147  virginica         5.2         2.0          NaN         3.0
148  virginica         5.4         2.3          NaN         3.4
149  virginica         5.1         1.8          NaN         3.0

[150 rows x 5 columns]

This still has the buggy data.

Let's say that we have a couple friends who have already corrected this data for us.

# Fisher

Fisher has already given us one source of data:

<img src='data-sci-images/fisher-table-all.png' style='height:500px'>

Um....

That requires us to convert an image with text into an array of data..... let's not do that (though there are libraries and applications for doing optical character recognition and importing images!)

# Colleague #1

One of our colleagues has given us a JSON file.

In [3]:
import json

In [4]:
with open('data/iris-v1.json') as f:
    x = json.load(f)

In [5]:
x

{'measurements': ['petalLength', 'petalWidth', 'sepalLength', 'sepalWidth'],
 'setosa': [[1.4, 0.2, 5.1, 3.5],
  [1.4, 0.2, 4.9, 3.0],
  [1.3, 0.2, 4.7, 3.2],
  [1.5, 0.2, 4.6, 3.1],
  [1.4, 0.2, 5.0, 3.6],
  [1.7000000000000002, 0.4, 5.4, 3.9],
  [1.4, 0.30000000000000004, 4.6, 3.4],
  [1.5, 0.2, 5.0, 3.4],
  [1.4, 0.2, 4.4, 2.9],
  [1.5, 0.1, 4.9, 3.1],
  [1.5, 0.2, 5.4, 3.7],
  [1.6, 0.2, 4.8, 3.4],
  [1.4, 0.1, 4.8, 3.0],
  [1.1, 0.1, 4.3, 3.0],
  [1.2, 0.2, 5.8, 4.0],
  [1.5, 0.4, 5.7, 4.4],
  [1.3, 0.4, 5.4, 3.9],
  [1.4, 0.30000000000000004, 5.1, 3.5],
  [1.7000000000000002, 0.30000000000000004, 5.7, 3.8],
  [1.5, 0.30000000000000004, 5.1, 3.8],
  [1.7000000000000002, 0.2, 5.4, 3.4],
  [1.5, 0.4, 5.1, 3.7],
  [1.0, 0.2, 4.6, 3.6],
  [1.7000000000000002, 0.5, 5.1, 3.3],
  [1.9, 0.2, 4.8, 3.4],
  [1.6, 0.2, 5.0, 3.0],
  [1.6, 0.4, 5.0, 3.4],
  [1.5, 0.2, 5.2, 3.5],
  [1.4, 0.2, 5.2, 3.4],
  [1.6, 0.2, 4.7, 3.2],
  [1.6, 0.2, 4.8, 3.1],
  [1.5, 0.4, 5.4, 3.4],
  [1.5, 0.1, 5.2, 4.1],
  [1.4, 0.2, 5.5, 4.2],
  [1.5, 0.2, 4.9, 3.1],
  [1.2, 0.2, 5.0, 3.2],
  [1.3, 0.2, 5.5, 3.5],
  [1.4, 0.1, 4.9, 3.6],
  [1.3, 0.2, 4.4, 3.0],
  [1.5, 0.2, 5.1, 3.4],
  [1.3, 0.30000000000000004, 5.0, 3.5],
  [1.3, 0.30000000000000004, 4.5, 2.3],
  [1.3, 0.2, 4.4, 3.2],
  [1.6, 0.6000000000000001, 5.0, 3.5],
  [1.9, 0.4, 5.1, 3.8],
  [1.4, 0.30000000000000004, 4.8, 3.0],
  [1.6, 0.2, 5.1, 3.8],
  [1.4, 0.2, 4.6, 3.2],
  [1.5, 0.2, 5.3, 3.7],
  [1.4, 0.2, 5.0, 3.3]],
 'versicolor': [[4.7, 1.4, 7.0, 3.2],
  [4.5, 1.5, 6.4, 3.2],
  [4.9, 1.5, 6.9, 3.1],
  [4.0, 1.3, 5.5, 2.3],
  [4.6, 1.5, 6.5, 2.8],
  [4.5, 1.3, 5.7, 2.8],
  [4.7, 1.6, 6.3, 3.3],
  [3.3, 1.0, 4.9, 2.4],
  [4.6, 1.3, 6.6, 2.9],
  [3.9, 1.4, 5.2, 2.7],
  [3.5, 1.0, 5.0, 2.0],
  [4.2, 1.5, 5.9, 3.0],
  [4.0, 1.0, 6.0, 2.2],
  [4.7, 1.4, 6.1, 2.9],
  [3.6, 1.3, 5.6, 2.9],
  [4.4, 1.4, 6.7, 3.1],
  [4.5, 1.5, 5.6, 3.0],
  [4.1, 1.0, 5.8, 2.7],
  [4.5, 1.5, 6.2, 2.2],
  [3.9, 1.1, 5.6, 2.5],
  [4.8, 1.8, 5.9, 3.2],
  [4.0, 1.3, 6.1, 2.8],
  [4.9, 1.5, 6.3, 2.5],
  [4.7, 1.2, 6.1, 2.8],
  [4.3, 1.3, 6.4, 2.9],
  [4.4, 1.4, 6.6, 3.0],
  [4.8, 1.4, 6.8, 2.8],
  [5.0, 1.7000000000000002, 6.7, 3.0],
  [4.5, 1.5, 6.0, 2.9],
  [3.5, 1.0, 5.7, 2.6],
  [3.8, 1.1, 5.5, 2.4],
  [3.7, 1.0, 5.5, 2.4],
  [3.9, 1.2, 5.8, 2.7],
  [5.1, 1.6, 6.0, 2.7],
  [4.5, 1.5, 5.4, 3.0],
  [4.5, 1.6, 6.0, 3.4],
  [4.7, 1.5, 6.7, 3.1],
  [4.4, 1.3, 6.3, 2.3],
  [4.1, 1.3, 5.6, 3.0],
  [4.0, 1.3, 5.5, 2.5],
  [4.4, 1.2, 5.5, 2.6],
  [4.6, 1.4, 6.1, 3.0],
  [4.0, 1.2, 5.8, 2.6],
  [3.3, 1.0, 5.0, 2.3],
  [4.2, 1.3, 5.6, 2.7],
  [4.2, 1.2, 5.7, 3.0],
  [4.2, 1.3, 5.7, 2.9],
  [4.3, 1.3, 6.2, 2.9],
  [3.0, 1.1, 5.1, 2.5],
  [4.1, 1.3, 5.7, 2.8]],
 'virginica': [[6.0, 2.5, 6.3, 3.3],
  [5.1, 1.9, 5.8, 2.7],
  [5.9, 2.1, 7.1, 3.0],
  [5.6, 1.8, 6.3, 2.9],
  [5.8, 2.2, 6.5, 3.0],
  [6.6, 2.1, 7.6, 3.0],
  [4.5, 1.7000000000000002, 4.9, 2.5],
  [6.3, 1.8, 7.3, 2.9],
  [5.8, 1.8, 6.7, 2.5],
  [6.1, 2.5, 7.2, 3.6],
  [5.1, 2.0, 6.5, 3.2],
  [5.3, 1.9, 6.4, 2.7],
  [5.5, 2.1, 6.8, 3.0],
  [5.0, 2.0, 5.7, 2.5],
  [5.1, 2.4, 5.8, 2.8],
  [5.3, 2.3, 6.4, 3.2],
  [5.5, 1.8, 6.5, 3.0],
  [6.7, 2.2, 7.7, 3.8],
  [6.9, 2.3, 7.7, 2.6],
  [5.0, 1.5, 6.0, 2.2],
  [5.7, 2.3, 6.9, 3.2],
  [4.9, 2.0, 5.6, 2.8],
  [6.7, 2.0, 7.7, 2.8],
  [4.9, 1.8, 6.3, 2.7],
  [5.7, 2.1, 6.7, 3.3],
  [6.0, 1.8, 7.2, 3.2],
  [4.8, 1.8, 6.2, 2.8],
  [4.9, 1.8, 6.1, 3.0],
  [5.6, 2.1, 6.4, 2.8],
  [5.8, 1.6, 7.2, 3.0],
  [6.1, 1.9, 7.4, 2.8],
  [6.4, 2.0, 7.9, 3.8],
  [5.6, 2.2, 6.4, 2.8],
  [5.1, 1.5, 6.3, 2.8],
  [5.6, 1.4, 6.1, 2.6],
  [6.1, 2.3, 7.7, 3.0],
  [5.6, 2.4, 6.3, 3.4],
  [5.5, 1.8, 6.4, 3.1],
  [4.8, 1.8, 6.0, 3.0],
  [5.4, 2.1, 6.9, 3.1],
  [5.6, 2.4, 6.7, 3.1],
  [5.1, 2.3, 6.9, 3.1],
  [5.1, 1.9, 5.8, 2.7],
  [5.9, 2.3, 6.8, 3.2],
  [5.7, 2.5, 6.7, 3.3],
  [5.2, 2.3, 6.7, 3.0],
  [5.0, 1.9, 6.3, 2.5],
  [5.2, 2.0, 6.5, 3.0],
  [5.4, 2.3, 6.2, 3.4],
  [5.1, 1.8, 5.9, 3.0]]}

Putting this into a DataFrame requires that we flatten the dictionary....

In [6]:
pd.read_json('data/iris-v1.json')

ValueError: arrays must all be same length

Apparently Pandas by default wants us to do that too.

In [8]:
pd.read_json('data/iris-v1-Copy1.json')

,setosa,versicolor,virginica
0,"[1.4, 0.2, 5.1, 3.5]","[4.7, 1.4, 7.0, 3.2]","[6.0, 2.5, 6.3, 3.3]"
1,"[1.4, 0.2, 4.9, 3.0]","[4.5, 1.5, 6.4, 3.2]","[5.1, 1.9, 5.8, 2.7]"
2,"[1.3, 0.2, 4.7, 3.2]","[4.9, 1.5, 6.9, 3.1]","[5.9, 2.1, 7.1, 3.0]"
3,"[1.5, 0.2, 4.6, 3.1]","[4.0, 1.3, 5.5, 2.3]","[5.6, 1.8, 6.3, 2.9]"
4,"[1.4, 0.2, 5.0, 3.6]","[4.6, 1.5, 6.5, 2.8]","[5.8, 2.2, 6.5, 3.0]"
5,"[1.7000000000000002, 0.4, 5.4, 3.9]","[4.5, 1.3, 5.7, 2.8]","[6.6, 2.1, 7.6, 3.0]"
6,"[1.4, 0.30000000000000004, 4.6, 3.4]","[4.7, 1.6, 6.3, 3.3]","[4.5, 1.7000000000000002, 4.9, 2.5]"
7,"[1.5, 0.2, 5.0, 3.4]","[3.3, 1.0, 4.9, 2.4]","[6.3, 1.8, 7.3, 2.9]"
8,"[1.4, 0.2, 4.4, 2.9]","[4.6, 1.3, 6.6, 2.9]","[5.8, 1.8, 6.7, 2.5]"
9,"[1.5, 0.1, 4.9, 3.1]","[3.9, 1.4, 5.2, 2.7]","[6.1, 2.5, 7.2, 3.6]"
10,"[1.5, 0.2, 5.4, 3.7]","[3.5, 1.0, 5.0, 2.0]","[5.1, 2.0, 6.5, 3.2]"
11,"[1.6, 0.2, 4.8, 3.4]","[4.2, 1.5, 5.9, 3.0]","[5.3, 1.9, 6.4, 2.7]"
12,"[1.4, 0.1, 4.8, 3.0]","[4.0, 1.0, 6.0, 2.2]","[5.5, 2.1, 6.8, 3.0]"
13,"[1.1, 0.1, 4.3, 3.0]","[4.7, 1.4, 6.1, 2.9]","[5.0, 2.0, 5.7, 2.5]"
14,"[1.2, 0.2, 5.8, 4.0]","[3.6, 1.3, 5.6, 2.9]","[5.1, 2.4, 5.8, 2.8]"
15,"[1.5, 0.4, 5.7, 4.4]","[4.4, 1.4, 6.7, 3.1]","[5.3, 2.3, 6.4, 3.2]"
16,"[1.3, 0.4, 5.4, 3.9]","[4.5, 1.5, 5.6, 3.0]","[5.5, 1.8, 6.5, 3.0]"
17,"[1.4, 0.30000000000000004, 5.1, 3.5]","[4.1, 1.0, 5.8, 2.7]","[6.7, 2.2, 7.7, 3.8]"
18,"[1.7000000000000002, 0.30000000000000004, 5.7,...","[4.5, 1.5, 6.2, 2.2]","[6.9, 2.3, 7.7, 2.6]"
19,"[1.5, 0.30000000000000004, 5.1, 3.8]","[3.9, 1.1, 5.6, 2.5]","[5.0, 1.5, 6.0, 2.2]"
20,"[1.7000000000000002, 0.2, 5.4, 3.4]","[4.8, 1.8, 5.9, 3.2]","[5.7, 2.3, 6.9, 3.2]"
21,"[1.5, 0.4, 5.1, 3.7]","[4.0, 1.3, 6.1, 2.8]","[4.9, 2.0, 5.6, 2.8]"
22,"[1.0, 0.2, 4.6, 3.6]","[4.9, 1.5, 6.3, 2.5]","[6.7, 2.0, 7.7, 2.8]"
23,"[1.7000000000000002, 0.5, 5.1, 3.3]","[4.7, 1.2, 6.1, 2.8]","[4.9, 1.8, 6.3, 2.7]"
24,"[1.9, 0.2, 4.8, 3.4]","[4.3, 1.3, 6.4, 2.9]","[5.7, 2.1, 6.7, 3.3]"
25,"[1.6, 0.2, 5.0, 3.0]","[4.4, 1.4, 6.6, 3.0]","[6.0, 1.8, 7.2, 3.2]"
26,"[1.6, 0.4, 5.0, 3.4]","[4.8, 1.4, 6.8, 2.8]","[4.8, 1.8, 6.2, 2.8]"
27,"[1.5, 0.2, 5.2, 3.5]","[5.0, 1.7000000000000002, 6.7, 3.0]","[4.9, 1.8, 6.1, 3.0]"
28,"[1.4, 0.2, 5.2, 3.4]","[4.5, 1.5, 6.0, 2.9]","[5.6, 2.1, 6.4, 2.8]"
29,"[1.6, 0.2, 4.7, 3.2]","[3.5, 1.0, 5.7, 2.6]","[5.8, 1.6, 7.2, 3.0]"
30,"[1.6, 0.2, 4.8, 3.1]","[3.8, 1.1, 5.5, 2.4]","[6.1, 1.9, 7.4, 2.8]"
31,"[1.5, 0.4, 5.4, 3.4]","[3.7, 1.0, 5.5, 2.4]","[6.4, 2.0, 7.9, 3.8]"
32,"[1.5, 0.1, 5.2, 4.1]","[3.9, 1.2, 5.8, 2.7]","[5.6, 2.2, 6.4, 2.8]"
33,"[1.4, 0.2, 5.5, 4.2]","[5.1, 1.6, 6.0, 2.7]","[5.1, 1.5, 6.3, 2.8]"
34,"[1.5, 0.2, 4.9, 3.1]","[4.5, 1.5, 5.4, 3.0]","[5.6, 1.4, 6.1, 2.6]"
35,"[1.2, 0.2, 5.0, 3.2]","[4.5, 1.6, 6.0, 3.4]","[6.1, 2.3, 7.7, 3.0]"
36,"[1.3, 0.2, 5.5, 3.5]","[4.7, 1.5, 6.7, 3.1]","[5.6, 2.4, 6.3, 3.4]"
37,"[1.4, 0.1, 4.9, 3.6]","[4.4, 1.3, 6.3, 2.3]","[5.5, 1.8, 6.4, 3.1]"
38,"[1.3, 0.2, 4.4, 3.0]","[4.1, 1.3, 5.6, 3.0]","[4.8, 1.8, 6.0, 3.0]"
39,"[1.5, 0.2, 5.1, 3.4]","[4.0, 1.3, 5.5, 2.5]","[5.4, 2.1, 6.9, 3.1]"
40,"[1.3, 0.30000000000000004, 5.0, 3.5]","[4.4, 1.2, 5.5, 2.6]","[5.6, 2.4, 6.7, 3.1]"
41,"[1.3, 0.30000000000000004, 4.5, 2.3]","[4.6, 1.4, 6.1, 3.0]","[5.1, 2.3, 6.9, 3.1]"
42,"[1.3, 0.2, 4.4, 3.2]","[4.0, 1.2, 5.8, 2.6]","[5.1, 1.9, 5.8, 2.7]"
43,"[1.6, 0.6000000000000001, 5.0, 3.5]","[3.3, 1.0, 5.0, 2.3]","[5.9, 2.3, 6.8, 3.2]"
44,"[1.9, 0.4, 5.1, 3.8]","[4.2, 1.3, 5.6, 2.7]","[5.7, 2.5, 6.7, 3.3]"
45,"[1.4, 0.30000000000000004, 4.8, 3.0]","[4.2, 1.2, 5.7, 3.0]","[5.2, 2.3, 6.7, 3.0]"
46,"[1.6, 0.2, 5.1, 3.8]","[4.2, 1.3, 5.7, 2.9]","[5.0, 1.9, 6.3, 2.5]"
47,"[1.4, 0.2, 4.6, 3.2]","[4.3, 1.3, 6.2, 2.9]","[5.2, 2.0, 6.5, 3.0]"
48,"[1.5, 0.2, 5.3, 3.7]","[3.0, 1.1, 5.1, 2.5]","[5.4, 2.3, 6.2, 3.4]"
49,"[1.4, 0.2, 5.0, 3.3]","[4.1, 1.3, 5.7, 2.8]","[5.1, 1.8, 5.9, 3.0]"

We could do more, but let's move on.  If you would like to work through some details, check this out:

In [9]:
pd.read_json('data/iris-v2.json')

       species  petalLength  petalWidth  sepalLength  sepalWidth
0       setosa          1.4         0.2          5.1         3.5
1       setosa          1.4         0.2          4.9         3.0
2       setosa          1.3         0.2          4.7         3.2
3       setosa          1.5         0.2          4.6         3.1
4       setosa          1.4         0.2          5.0         3.6
..         ...          ...         ...          ...         ...
145  virginica          5.2         2.3          6.7         3.0
146  virginica          5.0         1.9          6.3         2.5
147  virginica          5.2         2.0          6.5         3.0
148  virginica          5.4         2.3          6.2         3.4
149  virginica          5.1         1.8          5.9         3.0

[150 rows x 5 columns]

But let's try another data set.

# Colleague #2

Another of our colleagues has given use a CSV.

In [10]:
import csv

In [11]:
with open('data/iris.csv') as f:
    x = csv.reader(f)

In [12]:
x

In [13]:
with open('data/iris.csv') as f:
    x = csv.reader(f)
    for row in x:
        print(row)

['petalLength', 'petalWidth', 'sepalLength', 'sepalWidth', 'species']
['1.4', '0.2', '5.1', '3.5', 'setosa']
['1.4', '0.2', '4.9', '3.0', 'setosa']
['1.3', '0.2', '4.7', '3.2', 'setosa']
['1.5', '0.2', '4.6', '3.1', 'setosa']
['1.4', '0.2', '5.0', '3.6', 'setosa']
['1.7', '0.4', '5.4', '3.9', 'setosa']
['1.4', '0.3', '4.6', '3.4', 'setosa']
['1.5', '0.2', '5.0', '3.4', 'setosa']
['1.4', '0.2', '4.4', '2.9', 'setosa']
['1.5', '0.1', '4.9', '3.1', 'setosa']
['1.5', '0.2', '5.4', '3.7', 'setosa']
['1.6', '0.2', '4.8', '3.4', 'setosa']
['1.4', '0.1', '4.8', '3.0', 'setosa']
['1.1', '0.1', '4.3', '3.0', 'setosa']
['1.2', '0.2', '5.8', '4.0', 'setosa']
['1.5', '0.4', '5.7', '4.4', 'setosa']
['1.3', '0.4', '5.4', '3.9', 'setosa']
['1.4', '0.3', '5.1', '3.5', 'setosa']
['1.7', '0.3', '5.7', '3.8', 'setosa']
['1.5', '0.3', '5.1', '3.8', 'setosa']
['1.7', '0.2', '5.4', '3.4', 'setosa']
['1.5', '0.4', '5.1', '3.7', 'setosa']
['1.0', '0.2', '4.6', '3.6', 'setosa']
['1.7', '0.5', '5.1', '3.3', 'setosa']
['1.9', '0.2', '4.8', '3.4', 'setosa']
['1.6', '0.2', '5.0', '3.0', 'setosa']
['1.6', '0.4', '5.0', '3.4', 'setosa']
['1.5', '0.2', '5.2', '3.5', 'setosa']
['1.4', '0.2', '5.2', '3.4', 'setosa']
['1.6', '0.2', '4.7', '3.2', 'setosa']
['1.6', '0.2', '4.8', '3.1', 'setosa']
['1.5', '0.4', '5.4', '3.4', 'setosa']
['1.5', '0.1', '5.2', '4.1', 'setosa']
['1.4', '0.2', '5.5', '4.2', 'setosa']
['1.5', '0.2', '4.9', '3.1', 'setosa']
['1.2', '0.2', '5.0', '3.2', 'setosa']
['1.3', '0.2', '5.5', '3.5', 'setosa']
['1.4', '0.1', '4.9', '3.6', 'setosa']
['1.3', '0.2', '4.4', '3.0', 'setosa']
['1.5', '0.2', '5.1', '3.4', 'setosa']
['1.3', '0.3', '5.0', '3.5', 'setosa']
['1.3', '0.3', '4.5', '2.3', 'setosa']
['1.3', '0.2', '4.4', '3.2', 'setosa']
['1.6', '0.6', '5.0', '3.5', 'setosa']
['1.9', '0.4', '5.1', '3.8', 'setosa']
['1.4', '0.3', '4.8', '3.0', 'setosa']
['1.6', '0.2', '5.1', '3.8', 'setosa']
['1.4', '0.2', '4.6', '3.2', 'setosa']
['1.5', '0.2', '5.3', '3.7', 'setosa']
['1.4', '0.2', '5.0', '3.3', 'setosa']
['4.7', '1.4', '7.0', '3.2', 'versicolor']
['4.5', '1.5', '6.4', '3.2', 'versicolor']
['4.9', '1.5', '6.9', '3.1', 'versicolor']
['4.0', '1.3', '5.5', '2.3', 'versicolor']
['4.6', '1.5', '6.5', '2.8', 'versicolor']
['4.5', '1.3', '5.7', '2.8', 'versicolor']
['4.7', '1.6', '6.3', '3.3', 'versicolor']
['3.3', '1.0', '4.9', '2.4', 'versicolor']
['4.6', '1.3', '6.6', '2.9', 'versicolor']
['3.9', '1.4', '5.2', '2.7', 'versicolor']
['3.5', '1.0', '5.0', '2.0', 'versicolor']
['4.2', '1.5', '5.9', '3.0', 'versicolor']
['4.0', '1.0', '6.0', '2.2', 'versicolor']
['4.7', '1.4', '6.1', '2.9', 'versicolor']
['3.6', '1.3', '5.6', '2.9', 'versicolor']
['4.4', '1.4', '6.7', '3.1', 'versicolor']
['4.5', '1.5', '5.6', '3.0', 'versicolor']
['4.1', '1.0', '5.8', '2.7', 'versicolor']
['4.5', '1.5', '6.2', '2.2', 'versicolor']
['3.9', '1.1', '5.6', '2.5', 'versicolor']
['4.8', '1.8', '5.9', '3.2', 'versicolor']
['4.0', '1.3', '6.1', '2.8', 'versicolor']
['4.9', '1.5', '6.3', '2.5', 'versicolor']
['4.7', '1.2', '6.1', '2.8', 'versicolor']
['4.3', '1.3', '6.4', '2.9', 'versicolor']
['4.4', '1.4', '6.6', '3.0', 'versicolor']
['4.8', '1.4', '6.8', '2.8', 'versicolor']
['5.0', '1.7', '6.7', '3.0', 'versicolor']
['4.5', '1.5', '6.0', '2.9', 'versicolor']
['3.5', '1.0', '5.7', '2.6', 'versicolor']
['3.8', '1.1', '5.5', '2.4', 'versicolor']
['3.7', '1.0', '5.5', '2.4', 'versicolor']
['3.9', '1.2', '5.8', '2.7', 'versicolor']
['5.1', '1.6', '6.0', '2.7', 'versicolor']
['4.5', '1.5', '5.4', '3.0', 'versicolor']
['4.5', '1.6', '6.0', '3.4', 'versicolor']
['4.7', '1.5', '6.7', '3.1', 'versicolor']
['4.4', '1.3', '6.3', '2.3', 'versicolor']
['4.1', '1.3', '5.6', '3.0', 'versicolor']
['4.0', '1.3', '5.5', '2.5', 'versicolor']
['4.4', '1.2', '5.5', '2.6', 'versicolor']
['4.6', '1.4', '6.1', '3.0', 'versicolor']
['4.0', '1.2', '5.8', '2.6', 'versicolor']
['3.3', '1.0', '5.0', '2.3', 'versicolor']
['4.2', '1.3', '5.6', '2.7', 'versicolor']
['4.2', '1.2', '5.7', '3.0', 'versicolor']
['4.2', '1.3', '5.7', '2.9', 'versicolor']
['4.3', '1.3', '6.2', '2.9', 'versicolor']
['3.0', '1.1', '5.1', '2.5', 'versicolor']
['4.1', '1.3', '5.7', '2.8', 'versicolor']
['6.0', '2.5', '6.3', '3.3', 'virginica']
['5.1', '1.9', '5.8', '2.7', 'virginica']
['5.9', '2.1', '7.1', '3.0', 'virginica']
['5.6', '1.8', '6.3', '2.9', 'virginica']
['5.8', '2.2', '6.5', '3.0', 'virginica']
['6.6', '2.1', '7.6', '3.0', 'virginica']
['4.5', '1.7', '4.9', '2.5', 'virginica']
['6.3', '1.8', '7.3', '2.9', 'virginica']
['5.8', '1.8', '6.7', '2.5', 'virginica']
['6.1', '2.5', '7.2', '3.6', 'virginica']
['5.1', '2.0', '6.5', '3.2', 'virginica']
['5.3', '1.9', '6.4', '2.7', 'virginica']
['5.5', '2.1', '6.8', '3.0', 'virginica']
['5.0', '2.0', '5.7', '2.5', 'virginica']
['5.1', '2.4', '5.8', '2.8', 'virginica']
['5.3', '2.3', '6.4', '3.2', 'virginica']
['5.5', '1.8', '6.5', '3.0', 'virginica']
['6.7', '2.2', '7.7', '3.8', 'virginica']
['6.9', '2.3', '7.7', '2.6', 'virginica']
['5.0', '1.5', '6.0', '2.2', 'virginica']
['5.7', '2.3', '6.9', '3.2', 'virginica']
['4.9', '2.0', '5.6', '2.8', 'virginica']
['6.7', '2.0', '7.7', '2.8', 'virginica']
['4.9', '1.8', '6.3', '2.7', 'virginica']
['5.7', '2.1', '6.7', '3.3', 'virginica']
['6.0', '1.8', '7.2', '3.2', 'virginica']
['4.8', '1.8', '6.2', '2.8', 'virginica']
['4.9', '1.8', '6.1', '3.0', 'virginica']
['5.6', '2.1', '6.4', '2.8', 'virginica']
['5.8', '1.6', '7.2', '3.0', 'virginica']
['6.1', '1.9', '7.4', '2.8', 'virginica']
['6.4', '2.0', '7.9', '3.8', 'virginica']
['5.6', '2.2', '6.4', '2.8', 'virginica']
['5.1', '1.5', '6.3', '2.8', 'virginica']
['5.6', '1.4', '6.1', '2.6', 'virginica']
['6.1', '2.3', '7.7', '3.0', 'virginica']
['5.6', '2.4', '6.3', '3.4', 'virginica']
['5.5', '1.8', '6.4', '3.1', 'virginica']
['4.8', '1.8', '6.0', '3.0', 'virginica']
['5.4', '2.1', '6.9', '3.1', 'virginica']
['5.6', '2.4', '6.7', '3.1', 'virginica']
['5.1', '2.3', '6.9', '3.1', 'virginica']
['5.1', '1.9', '5.8', '2.7', 'virginica']
['5.9', '2.3', '6.8', '3.2', 'virginica']
['5.7', '2.5', '6.7', '3.3', 'virginica']
['5.2', '2.3', '6.7', '3.0', 'virginica']
['5.0', '1.9', '6.3', '2.5', 'virginica']
['5.2', '2.0', '6.5', '3.0', 'virginica']
['5.4', '2.3', '6.2', '3.4', 'virginica']
['5.1', '1.8', '5.9', '3.0', 'virginica']

In [14]:
csvlists = []
with open('data/iris.csv') as f:
    x = csv.reader(f)
    for row in x:
        csvlists.append(row)
dfcsv = pd.DataFrame(csvlists[1:],columns=csvlists[0])

In [15]:
dfcsv

    petalLength petalWidth sepalLength sepalWidth    species
0           1.4        0.2         5.1        3.5     setosa
1           1.4        0.2         4.9        3.0     setosa
2           1.3        0.2         4.7        3.2     setosa
3           1.5        0.2         4.6        3.1     setosa
4           1.4        0.2         5.0        3.6     setosa
..          ...        ...         ...        ...        ...
145         5.2        2.3         6.7        3.0  virginica
146         5.0        1.9         6.3        2.5  virginica
147         5.2        2.0         6.5        3.0  virginica
148         5.4        2.3         6.2        3.4  virginica
149         5.1        1.8         5.9        3.0  virginica

[150 rows x 5 columns]

...or ....

In [16]:
pd.read_csv('data/iris.csv')

     petalLength  petalWidth  sepalLength  sepalWidth    species
0            1.4         0.2          5.1         3.5     setosa
1            1.4         0.2          4.9         3.0     setosa
2            1.3         0.2          4.7         3.2     setosa
3            1.5         0.2          4.6         3.1     setosa
4            1.4         0.2          5.0         3.6     setosa
..           ...         ...          ...         ...        ...
145          5.2         2.3          6.7         3.0  virginica
146          5.0         1.9          6.3         2.5  virginica
147          5.2         2.0          6.5         3.0  virginica
148          5.4         2.3          6.2         3.4  virginica
149          5.1         1.8          5.9         3.0  virginica

[150 rows x 5 columns]

# Colleague #3

Colleague #3 exported tab-separated values.

(Look at 'data/iris-tab.txt')

In [17]:
pd.read_csv('data/iris-tab.txt',delimiter='\t')

       species  petalLength  petalWidth  sepalLength  sepalWidth
0       setosa          1.4         0.2          5.1         3.5
1       setosa          1.4         0.2          4.9         3.0
2       setosa          1.3         0.2          4.7         3.2
3       setosa          1.5         0.2          4.6         3.1
4       setosa          1.4         0.2          5.0         3.6
..         ...          ...         ...          ...         ...
145  virginica          5.2         2.3          6.7         3.0
146  virginica          5.0         1.9          6.3         2.5
147  virginica          5.2         2.0          6.5         3.0
148  virginica          5.4         2.3          6.2         3.4
149  virginica          5.1         1.8          5.9         3.0

[150 rows x 5 columns]

# Online resources

Let's say we're uneasy about consulting our colleagues on this one.

The UCI machine learning repository hosts this data.

https://archive.ics.uci.edu/ml/datasets/iris

In Python, you can execute shell commands.  For example, let's execute a command with wget.

In [18]:
!wget https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.names

--2020-08-18 06:29:01--  https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.names
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2998 (2.9K) [application/x-httpd-php]
Saving to: â€˜iris.names.3â€™

iris.names.3        100%[===================>]   2.93K  --.-KB/s    in 0s

2020-08-18 06:29:01 (54.2 MB/s) - â€˜iris.names.3â€™ saved [2998/2998]

"GNU Wget is a free software package for retrieving files using HTTP, HTTPS, FTP and FTPS, the most widely used Internet protocols. It is a non-interactive commandline tool, so it may easily be called from scripts, cron jobs, terminals without X-Windows support, etc."
<br>-- https://www.gnu.org/software/wget/

The above uses "!" to execute shell commands from this notebook.

The way to run shell commands from a Python program:
* use `os.system()`
* use `os.popen()`
* use the `subprocess` module

In [19]:
import os

In [20]:
os.system('wget https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.names')

0

Consulting that file -- it's a text file, and gives us good information, but maybe more than we want right now.

In [21]:
import requests

In [22]:
x = requests.get('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data')

In [23]:
x

In [24]:
print(x.content)

b'5.1,3.5,1.4,0.2,Iris-setosa\n4.9,3.0,1.4,0.2,Iris-setosa\n4.7,3.2,1.3,0.2,Iris-setosa\n4.6,3.1,1.5,0.2,Iris-setosa\n5.0,3.6,1.4,0.2,Iris-setosa\n5.4,3.9,1.7,0.4,Iris-setosa\n4.6,3.4,1.4,0.3,Iris-setosa\n5.0,3.4,1.5,0.2,Iris-setosa\n4.4,2.9,1.4,0.2,Iris-setosa\n4.9,3.1,1.5,0.1,Iris-setosa\n5.4,3.7,1.5,0.2,Iris-setosa\n4.8,3.4,1.6,0.2,Iris-setosa\n4.8,3.0,1.4,0.1,Iris-setosa\n4.3,3.0,1.1,0.1,Iris-setosa\n5.8,4.0,1.2,0.2,Iris-setosa\n5.7,4.4,1.5,0.4,Iris-setosa\n5.4,3.9,1.3,0.4,Iris-setosa\n5.1,3.5,1.4,0.3,Iris-setosa\n5.7,3.8,1.7,0.3,Iris-setosa\n5.1,3.8,1.5,0.3,Iris-setosa\n5.4,3.4,1.7,0.2,Iris-setosa\n5.1,3.7,1.5,0.4,Iris-setosa\n4.6,3.6,1.0,0.2,Iris-setosa\n5.1,3.3,1.7,0.5,Iris-setosa\n4.8,3.4,1.9,0.2,Iris-setosa\n5.0,3.0,1.6,0.2,Iris-setosa\n5.0,3.4,1.6,0.4,Iris-setosa\n5.2,3.5,1.5,0.2,Iris-setosa\n5.2,3.4,1.4,0.2,Iris-setosa\n4.7,3.2,1.6,0.2,Iris-setosa\n4.8,3.1,1.6,0.2,Iris-setosa\n5.4,3.4,1.5,0.4,Iris-setosa\n5.2,4.1,1.5,0.1,Iris-setosa\n5.5,4.2,1.4,0.2,Iris-setosa\n4.9,3.1,1.5,0.1,Iris-setosa\n5.0,3.2,1.2,0.2,Iris-setosa\n5.5,3.5,1.3,0.2,Iris-setosa\n4.9,3.1,1.5,0.1,Iris-setosa\n4.4,3.0,1.3,0.2,Iris-setosa\n5.1,3.4,1.5,0.2,Iris-setosa\n5.0,3.5,1.3,0.3,Iris-setosa\n4.5,2.3,1.3,0.3,Iris-setosa\n4.4,3.2,1.3,0.2,Iris-setosa\n5.0,3.5,1.6,0.6,Iris-setosa\n5.1,3.8,1.9,0.4,Iris-setosa\n4.8,3.0,1.4,0.3,Iris-setosa\n5.1,3.8,1.6,0.2,Iris-setosa\n4.6,3.2,1.4,0.2,Iris-setosa\n5.3,3.7,1.5,0.2,Iris-setosa\n5.0,3.3,1.4,0.2,Iris-setosa\n7.0,3.2,4.7,1.4,Iris-versicolor\n6.4,3.2,4.5,1.5,Iris-versicolor\n6.9,3.1,4.9,1.5,Iris-versicolor\n5.5,2.3,4.0,1.3,Iris-versicolor\n6.5,2.8,4.6,1.5,Iris-versicolor\n5.7,2.8,4.5,1.3,Iris-versicolor\n6.3,3.3,4.7,1.6,Iris-versicolor\n4.9,2.4,3.3,1.0,Iris-versicolor\n6.6,2.9,4.6,1.3,Iris-versicolor\n5.2,2.7,3.9,1.4,Iris-versicolor\n5.0,2.0,3.5,1.0,Iris-versicolor\n5.9,3.0,4.2,1.5,Iris-versicolor\n6.0,2.2,4.0,1.0,Iris-versicolor\n6.1,2.9,4.7,1.4,Iris-versicolor\n5.6,2.9,3.6,1.3,Iris-versicolor\n6.7,3.1,4.4,1.4,Iris-versicolor\n5.6,3.0,4.5,1.5,Iris-versicolor\n5.8,2.7,4.1,1.0,Iris-versicolor\n6.2,2.2,4.5,1.5,Iris-versicolor\n5.6,2.5,3.9,1.1,Iris-versicolor\n5.9,3.2,4.8,1.8,Iris-versicolor\n6.1,2.8,4.0,1.3,Iris-versicolor\n6.3,2.5,4.9,1.5,Iris-versicolor\n6.1,2.8,4.7,1.2,Iris-versicolor\n6.4,2.9,4.3,1.3,Iris-versicolor\n6.6,3.0,4.4,1.4,Iris-versicolor\n6.8,2.8,4.8,1.4,Iris-versicolor\n6.7,3.0,5.0,1.7,Iris-versicolor\n6.0,2.9,4.5,1.5,Iris-versicolor\n5.7,2.6,3.5,1.0,Iris-versicolor\n5.5,2.4,3.8,1.1,Iris-versicolor\n5.5,2.4,3.7,1.0,Iris-versicolor\n5.8,2.7,3.9,1.2,Iris-versicolor\n6.0,2.7,5.1,1.6,Iris-versicolor\n5.4,3.0,4.5,1.5,Iris-versicolor\n6.0,3.4,4.5,1.6,Iris-versicolor\n6.7,3.1,4.7,1.5,Iris-versicolor\n6.3,2.3,4.4,1.3,Iris-versicolor\n5.6,3.0,4.1,1.3,Iris-versicolor\n5.5,2.5,4.0,1.3,Iris-versicolor\n5.5,2.6,4.4,1.2,Iris-versicolor\n6.1,3.0,4.6,1.4,Iris-versicolor\n5.8,2.6,4.0,1.2,Iris-versicolor\n5.0,2.3,3.3,1.0,Iris-versicolor\n5.6,2.7,4.2,1.3,Iris-versicolor\n5.7,3.0,4.2,1.2,Iris-versicolor\n5.7,2.9,4.2,1.3,Iris-versicolor\n6.2,2.9,4.3,1.3,Iris-versicolor\n5.1,2.5,3.0,1.1,Iris-versicolor\n5.7,2.8,4.1,1.3,Iris-versicolor\n6.3,3.3,6.0,2.5,Iris-virginica\n5.8,2.7,5.1,1.9,Iris-virginica\n7.1,3.0,5.9,2.1,Iris-virginica\n6.3,2.9,5.6,1.8,Iris-virginica\n6.5,3.0,5.8,2.2,Iris-virginica\n7.6,3.0,6.6,2.1,Iris-virginica\n4.9,2.5,4.5,1.7,Iris-virginica\n7.3,2.9,6.3,1.8,Iris-virginica\n6.7,2.5,5.8,1.8,Iris-virginica\n7.2,3.6,6.1,2.5,Iris-virginica\n6.5,3.2,5.1,2.0,Iris-virginica\n6.4,2.7,5.3,1.9,Iris-virginica\n6.8,3.0,5.5,2.1,Iris-virginica\n5.7,2.5,5.0,2.0,Iris-virginica\n5.8,2.8,5.1,2.4,Iris-virginica\n6.4,3.2,5.3,2.3,Iris-virginica\n6.5,3.0,5.5,1.8,Iris-virginica\n7.7,3.8,6.7,2.2,Iris-virginica\n7.7,2.6,6.9,2.3,Iris-virginica\n6.0,2.2,5.0,1.5,Iris-virginica\n6.9,3.2,5.7,2.3,Iris-virginica\n5.6,2.8,4.9,2.0,Iris-virginica\n7.7,2.8,6.7,2.0,Iris-virginica\n6.3,2.7,4.9,1.8,Iris-virginica\n6.7,3.3,5.7,2.1,Iris-virginica\n7.2,3.2,6.0,1.8,Iris-virginica\n6.2,2.8,4.8,1.8,Iris-virginica\n6.1,3.0,4.9,1.8,Iris-virginica\n6.4,2.8,5.6,2.1,Iris-virginica\n7.2,3.0,5.8,1.6,Iris-virginica\n7.4,2.8,6.1,1.9,Iris-virginica\n7.9,3.8,6.4,2.0,Iris-virginica\n6.4,2.8,5.6,2.2,Iris-virginica\n6.3,2.8,5.1,1.5,Iris-virginica\n6.1,2.6,5.6,1.4,Iris-virginica\n7.7,3.0,6.1,2.3,Iris-virginica\n6.3,3.4,5.6,2.4,Iris-virginica\n6.4,3.1,5.5,1.8,Iris-virginica\n6.0,3.0,4.8,1.8,Iris-virginica\n6.9,3.1,5.4,2.1,Iris-virginica\n6.7,3.1,5.6,2.4,Iris-virginica\n6.9,3.1,5.1,2.3,Iris-virginica\n5.8,2.7,5.1,1.9,Iris-virginica\n6.8,3.2,5.9,2.3,Iris-virginica\n6.7,3.3,5.7,2.5,Iris-virginica\n6.7,3.0,5.2,2.3,Iris-virginica\n6.3,2.5,5.0,1.9,Iris-virginica\n6.5,3.0,5.2,2.0,Iris-virginica\n6.2,3.4,5.4,2.3,Iris-virginica\n5.9,3.0,5.1,1.8,Iris-virginica\n\n'

In [25]:
x.text.split('\n')

['5.1,3.5,1.4,0.2,Iris-setosa',
 '4.9,3.0,1.4,0.2,Iris-setosa',
 '4.7,3.2,1.3,0.2,Iris-setosa',
 '4.6,3.1,1.5,0.2,Iris-setosa',
 '5.0,3.6,1.4,0.2,Iris-setosa',
 '5.4,3.9,1.7,0.4,Iris-setosa',
 '4.6,3.4,1.4,0.3,Iris-setosa',
 '5.0,3.4,1.5,0.2,Iris-setosa',
 '4.4,2.9,1.4,0.2,Iris-setosa',
 '4.9,3.1,1.5,0.1,Iris-setosa',
 '5.4,3.7,1.5,0.2,Iris-setosa',
 '4.8,3.4,1.6,0.2,Iris-setosa',
 '4.8,3.0,1.4,0.1,Iris-setosa',
 '4.3,3.0,1.1,0.1,Iris-setosa',
 '5.8,4.0,1.2,0.2,Iris-setosa',
 '5.7,4.4,1.5,0.4,Iris-setosa',
 '5.4,3.9,1.3,0.4,Iris-setosa',
 '5.1,3.5,1.4,0.3,Iris-setosa',
 '5.7,3.8,1.7,0.3,Iris-setosa',
 '5.1,3.8,1.5,0.3,Iris-setosa',
 '5.4,3.4,1.7,0.2,Iris-setosa',
 '5.1,3.7,1.5,0.4,Iris-setosa',
 '4.6,3.6,1.0,0.2,Iris-setosa',
 '5.1,3.3,1.7,0.5,Iris-setosa',
 '4.8,3.4,1.9,0.2,Iris-setosa',
 '5.0,3.0,1.6,0.2,Iris-setosa',
 '5.0,3.4,1.6,0.4,Iris-setosa',
 '5.2,3.5,1.5,0.2,Iris-setosa',
 '5.2,3.4,1.4,0.2,Iris-setosa',
 '4.7,3.2,1.6,0.2,Iris-setosa',
 '4.8,3.1,1.6,0.2,Iris-setosa',
 '5.4,3.4,1.5,0.4,Iris-setosa',
 '5.2,4.1,1.5,0.1,Iris-setosa',
 '5.5,4.2,1.4,0.2,Iris-setosa',
 '4.9,3.1,1.5,0.1,Iris-setosa',
 '5.0,3.2,1.2,0.2,Iris-setosa',
 '5.5,3.5,1.3,0.2,Iris-setosa',
 '4.9,3.1,1.5,0.1,Iris-setosa',
 '4.4,3.0,1.3,0.2,Iris-setosa',
 '5.1,3.4,1.5,0.2,Iris-setosa',
 '5.0,3.5,1.3,0.3,Iris-setosa',
 '4.5,2.3,1.3,0.3,Iris-setosa',
 '4.4,3.2,1.3,0.2,Iris-setosa',
 '5.0,3.5,1.6,0.6,Iris-setosa',
 '5.1,3.8,1.9,0.4,Iris-setosa',
 '4.8,3.0,1.4,0.3,Iris-setosa',
 '5.1,3.8,1.6,0.2,Iris-setosa',
 '4.6,3.2,1.4,0.2,Iris-setosa',
 '5.3,3.7,1.5,0.2,Iris-setosa',
 '5.0,3.3,1.4,0.2,Iris-setosa',
 '7.0,3.2,4.7,1.4,Iris-versicolor',
 '6.4,3.2,4.5,1.5,Iris-versicolor',
 '6.9,3.1,4.9,1.5,Iris-versicolor',
 '5.5,2.3,4.0,1.3,Iris-versicolor',
 '6.5,2.8,4.6,1.5,Iris-versicolor',
 '5.7,2.8,4.5,1.3,Iris-versicolor',
 '6.3,3.3,4.7,1.6,Iris-versicolor',
 '4.9,2.4,3.3,1.0,Iris-versicolor',
 '6.6,2.9,4.6,1.3,Iris-versicolor',
 '5.2,2.7,3.9,1.4,Iris-versicolor',
 '5.0,2.0,3.5,1.0,Iris-versicolor',
 '5.9,3.0,4.2,1.5,Iris-versicolor',
 '6.0,2.2,4.0,1.0,Iris-versicolor',
 '6.1,2.9,4.7,1.4,Iris-versicolor',
 '5.6,2.9,3.6,1.3,Iris-versicolor',
 '6.7,3.1,4.4,1.4,Iris-versicolor',
 '5.6,3.0,4.5,1.5,Iris-versicolor',
 '5.8,2.7,4.1,1.0,Iris-versicolor',
 '6.2,2.2,4.5,1.5,Iris-versicolor',
 '5.6,2.5,3.9,1.1,Iris-versicolor',
 '5.9,3.2,4.8,1.8,Iris-versicolor',
 '6.1,2.8,4.0,1.3,Iris-versicolor',
 '6.3,2.5,4.9,1.5,Iris-versicolor',
 '6.1,2.8,4.7,1.2,Iris-versicolor',
 '6.4,2.9,4.3,1.3,Iris-versicolor',
 '6.6,3.0,4.4,1.4,Iris-versicolor',
 '6.8,2.8,4.8,1.4,Iris-versicolor',
 '6.7,3.0,5.0,1.7,Iris-versicolor',
 '6.0,2.9,4.5,1.5,Iris-versicolor',
 '5.7,2.6,3.5,1.0,Iris-versicolor',
 '5.5,2.4,3.8,1.1,Iris-versicolor',
 '5.5,2.4,3.7,1.0,Iris-versicolor',
 '5.8,2.7,3.9,1.2,Iris-versicolor',
 '6.0,2.7,5.1,1.6,Iris-versicolor',
 '5.4,3.0,4.5,1.5,Iris-versicolor',
 '6.0,3.4,4.5,1.6,Iris-versicolor',
 '6.7,3.1,4.7,1.5,Iris-versicolor',
 '6.3,2.3,4.4,1.3,Iris-versicolor',
 '5.6,3.0,4.1,1.3,Iris-versicolor',
 '5.5,2.5,4.0,1.3,Iris-versicolor',
 '5.5,2.6,4.4,1.2,Iris-versicolor',
 '6.1,3.0,4.6,1.4,Iris-versicolor',
 '5.8,2.6,4.0,1.2,Iris-versicolor',
 '5.0,2.3,3.3,1.0,Iris-versicolor',
 '5.6,2.7,4.2,1.3,Iris-versicolor',
 '5.7,3.0,4.2,1.2,Iris-versicolor',
 '5.7,2.9,4.2,1.3,Iris-versicolor',
 '6.2,2.9,4.3,1.3,Iris-versicolor',
 '5.1,2.5,3.0,1.1,Iris-versicolor',
 '5.7,2.8,4.1,1.3,Iris-versicolor',
 '6.3,3.3,6.0,2.5,Iris-virginica',
 '5.8,2.7,5.1,1.9,Iris-virginica',
 '7.1,3.0,5.9,2.1,Iris-virginica',
 '6.3,2.9,5.6,1.8,Iris-virginica',
 '6.5,3.0,5.8,2.2,Iris-virginica',
 '7.6,3.0,6.6,2.1,Iris-virginica',
 '4.9,2.5,4.5,1.7,Iris-virginica',
 '7.3,2.9,6.3,1.8,Iris-virginica',
 '6.7,2.5,5.8,1.8,Iris-virginica',
 '7.2,3.6,6.1,2.5,Iris-virginica',
 '6.5,3.2,5.1,2.0,Iris-virginica',
 '6.4,2.7,5.3,1.9,Iris-virginica',
 '6.8,3.0,5.5,2.1,Iris-virginica',
 '5.7,2.5,5.0,2.0,Iris-virginica',
 '5.8,2.8,5.1,2.4,Iris-virginica',
 '6.4,3.2,5.3,2.3,Iris-virginica',
 '6.5,3.0,5.5,1.8,Iris-virginica',
 '7.7,3.8,6.7,2.2,Iris-virginica',
 '7.7,2.6,6.9,2.3,Iris-virginica',
 '6.0,2.2,5.0,1.5,Iris-virginica',
 '6.9,3.2,5.7,2.3,Iris-virginica',
 '5.6,2.8,4.9,2.0,Iris-virginica',
 '7.7,2.8,6.7,2.0,Iris-virginica',
 '6.3,2.7,4.9,1.8,Iris-virginica',
 '6.7,3.3,5.7,2.1,Iris-virginica',
 '7.2,3.2,6.0,1.8,Iris-virginica',
 '6.2,2.8,4.8,1.8,Iris-virginica',
 '6.1,3.0,4.9,1.8,Iris-virginica',
 '6.4,2.8,5.6,2.1,Iris-virginica',
 '7.2,3.0,5.8,1.6,Iris-virginica',
 '7.4,2.8,6.1,1.9,Iris-virginica',
 '7.9,3.8,6.4,2.0,Iris-virginica',
 '6.4,2.8,5.6,2.2,Iris-virginica',
 '6.3,2.8,5.1,1.5,Iris-virginica',
 '6.1,2.6,5.6,1.4,Iris-virginica',
 '7.7,3.0,6.1,2.3,Iris-virginica',
 '6.3,3.4,5.6,2.4,Iris-virginica',
 '6.4,3.1,5.5,1.8,Iris-virginica',
 '6.0,3.0,4.8,1.8,Iris-virginica',
 '6.9,3.1,5.4,2.1,Iris-virginica',
 '6.7,3.1,5.6,2.4,Iris-virginica',
 '6.9,3.1,5.1,2.3,Iris-virginica',
 '5.8,2.7,5.1,1.9,Iris-virginica',
 '6.8,3.2,5.9,2.3,Iris-virginica',
 '6.7,3.3,5.7,2.5,Iris-virginica',
 '6.7,3.0,5.2,2.3,Iris-virginica',
 '6.3,2.5,5.0,1.9,Iris-virginica',
 '6.5,3.0,5.2,2.0,Iris-virginica',
 '6.2,3.4,5.4,2.3,Iris-virginica',
 '5.9,3.0,5.1,1.8,Iris-virginica',
 '',
 '']

To make a DataFrame from a list, we need the list items (that is, the eventual rows) to be lists.

This can be obtained via list comprehension.

In [28]:
# Starter examples of list comprehension
[i for i in [1,2,3]]

[1, 2, 3]

In [29]:
[i for i in ['What,is,this','a,comma,full,sentence']]

['What,is,this', 'a,comma,full,sentence']

In [30]:
[i.split(',') for i in ['What,is,this','a,comma,full,sentence']]

[['What', 'is', 'this'], ['a', 'comma', 'full', 'sentence']]

In [32]:
xarr = [i.split(',') for i in x.text.split('\n')]

Essentially this is a Pythonic way of saying:
```
make a new list
whose elements are i.split(',')
-- e.g. ['5.1','3.5','1.4','0.2','Iris-setosa'] from '5.1,3.5,1.4,0.2,Iris-setosa'
for every element i from x.text.split('\n') 
-- e.g. the list of strings above
```

In [35]:
pd.DataFrame(xarr)

       0     1     2     3               4
0    5.1   3.5   1.4   0.2     Iris-setosa
1    4.9   3.0   1.4   0.2     Iris-setosa
2    4.7   3.2   1.3   0.2     Iris-setosa
3    4.6   3.1   1.5   0.2     Iris-setosa
4    5.0   3.6   1.4   0.2     Iris-setosa
..   ...   ...   ...   ...             ...
147  6.5   3.0   5.2   2.0  Iris-virginica
148  6.2   3.4   5.4   2.3  Iris-virginica
149  5.9   3.0   5.1   1.8  Iris-virginica
150       None  None  None            None
151       None  None  None            None

[152 rows x 5 columns]

In [36]:
pd.DataFrame(xarr).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 152 entries, 0 to 151
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       152 non-null    object
 1   1       150 non-null    object
 2   2       150 non-null    object
 3   3       150 non-null    object
 4   4       150 non-null    object
dtypes: object(5)
memory usage: 6.1+ KB

We should still fix the data types.

# Pandas through the web

Lo and behold, you can even pass a website into Panda's read_csv

In [37]:
irisdf = pd.read_csv('https://raw.githubusercontent.com/jbrownlee/Datasets/master/iris.csv')

For pd.read_csv, "Any valid string path is acceptable. The string could be a URL. Valid URL schemes include http, ftp, s3, gs, and file."
<br> --https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html

This means you can import from AWS S3 buckets too! (though this further requires installing S3Fs and handling authentication variables)

In [38]:
irisdf

     5.1  3.5  1.4  0.2     Iris-setosa
0    4.9  3.0  1.4  0.2     Iris-setosa
1    4.7  3.2  1.3  0.2     Iris-setosa
2    4.6  3.1  1.5  0.2     Iris-setosa
3    5.0  3.6  1.4  0.2     Iris-setosa
4    5.4  3.9  1.7  0.4     Iris-setosa
..   ...  ...  ...  ...             ...
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

[149 rows x 5 columns]

In [39]:
path = 'https://raw.githubusercontent.com/jbrownlee/Datasets/master/iris.csv'
irisdf = pd.read_csv(path, header=None)
irisdf.columns = ['sepalLength','sepalWidth','petalLength','petalWidth','species']

In [40]:
irisdf

     sepalLength  sepalWidth  petalLength  petalWidth         species
0            5.1         3.5          1.4         0.2     Iris-setosa
1            4.9         3.0          1.4         0.2     Iris-setosa
2            4.7         3.2          1.3         0.2     Iris-setosa
3            4.6         3.1          1.5         0.2     Iris-setosa
4            5.0         3.6          1.4         0.2     Iris-setosa
..           ...         ...          ...         ...             ...
145          6.7         3.0          5.2         2.3  Iris-virginica
146          6.3         2.5          5.0         1.9  Iris-virginica
147          6.5         3.0          5.2         2.0  Iris-virginica
148          6.2         3.4          5.4         2.3  Iris-virginica
149          5.9         3.0          5.1         1.8  Iris-virginica

[150 rows x 5 columns]

Pandas has many IO capabilities:

<img src='data-sci-images/pdio.png' width=700>

# There are many ways to grab data, and many places from which to grab it.

List of some interesting repositories:
* Socrata
* UCI ML repo
* yahoo finance if you're in business
....